// add PRODUCT data
export const CREATE_PRODUCT_DATA_START="CREATE_PRODUCT_DATA_START"
export const CREATE_PRODUCT_DATA_SUCCESS="CREATE_PRODUCT_DATA_SUCCESS"
export const CREATE_PRODUCT_DATA_ERROR="CREATE_PRODUCT_DATA_ERROR"

// get PRODUCT data
export const LOAD_PRODUCT_DATA_START="LOAD_PRODUCT_DATA_START"
export const LOAD_PRODUCT_DATA_SUCCESS="LOAD_PRODUCT_DATA_SUCCESS"
export const LOAD_PRODUCT_DATA_ERROR="LOAD_PRODUCT_DATA_ERROR"


// delete PRODUCT data
export const DELETE_PRODUCT_DATA_START="DELETE_PRODUCT_DATA_START"
export const DELETE_PRODUCT_DATA_SUCCESS="DELETE_PRODUCT_DATA_SUCCESS"
export const DELETE_PRODUCT_DATA_ERROR="DELETE_PRODUCT_DATA_ERROR"
// update PRODUCT data
export const UPDATE_PRODUCT_DATA_START="UPDATE_PRODUCT_DATA_START"
export const UPDATE_PRODUCT_DATA_SUCCESS="UPDATE_PRODUCT_DATA_SUCCESS"
export const UPDATE_PRODUCT_DATA_ERROR="UPDATE_PRODUCT_DATA_ERROR"
